### ISSUE TITLE
P2: Application Administration > Staff Type > In the Arabic form an error message is generated when the user clicks on the "Delete" button

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#127]
In the English form the user is able to delete a Staff type, However in the Arabic form an error message is generated and the user is not able to delete a staff type. (See attached screenshot)

![2015-01-09_15-11-07](https://cloud.githubusercontent.com/assets/3637417/5680085/b926b2de-9810-11e4-9a3c-48f8529fecf6.png)

**Comment by RaymondYounan** [comment]
Done.
I also updated the update that was creating the same error

**Comment by tannourynadine** [comment]
This issue is still reproducible for the update and delete Staff type for both the English and Arabic forms. (See attached screenshots)

![staff-type-1](https://cloud.githubusercontent.com/assets/3637417/5721475/dacdc940-9b3a-11e4-9693-88f36572d431.png)
![staff-type](https://cloud.githubusercontent.com/assets/3637417/5721476/dacfa224-9b3a-11e4-916e-aa4b90e88c8f.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified for both the English and Arabic forms that the user is able to create, edit and delete a Staff Type and no error message is generated.

**Comment by RaymondYounan** [comment]
@tannourynadine : Can you please close the verified issues?
Thanks
