### ISSUE TITLE
P4: Teachers >Teacher Management > The error messages generated when the user doesn’t enter information in a required field need to be translated in the "Create Teacher" Arabic form 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#144]
![teacher-management-ar](https://cloud.githubusercontent.com/assets/3637417/5718879/0e06fdce-9b1b-11e4-9929-363774900911.png)

![teacher-management-ar-2](https://cloud.githubusercontent.com/assets/3637417/5718973/025a2bbc-9b1c-11e4-81e4-5697a7a3b183.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the error messages generated at the "Person Details" section are translated, however, the error messages generated at the "Teacher Details" section are not translated. (Please see attached screenshot.)

![2015-02-20_10-14-03](https://cloud.githubusercontent.com/assets/3637417/6283098/138d35b6-b8e8-11e4-946d-3558cc1b4eb3.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
The issue related to the error messages generated at the "Teacher Details" section when the field length is exceeded is still reproducible.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that all the error messages generated are translated expect:
- The error message generated when the user enters an incorrect email address.
- The error message generated when the user enters an incorrect format for the graduation year.

**Comment by RaymondYounan** [comment]
Done
