### ISSUE TITLE
P4: Teachers >Teacher Management > Teacher Engagement > The error messages generated at the "Create Teacher Engagement" Arabic form should be translated

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#147]
![teacher-engament-ar-5](https://cloud.githubusercontent.com/assets/3637417/5720855/b58c02f8-9b32-11e4-8852-2f10c9a01b5e.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the error message generated are translated, however the error messages generated for  the fields with date pickers are not translated.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
The issue mentioned in my previous comment is still reproducible.
