### ISSUE TITLE
P3: Centers > Schools > Modify existing School > Country Field is blank

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#179]
Country drop down list is not loading the country value.

**Comment by DrJoeHage** [comment]
If you attempt to save, you get:
Error updating the School:Value cannot be null. Parameter name: String
Therefore, you need to re-select the country from the drop down.

**Comment by RaymondYounan** [comment]
The Dropdown list is generated both on the live website and on the development machine. Can you please specify the steps to reproduce the error?

**Comment by RaymondYounan** [comment]
@tannourynadine Can you please check if you can replicate this error?

**Comment by tannourynadine** [comment]
I could not reproduce the issue.

**Comment by tannourynadine** [comment]
I encountered a similar issue in the Application Administration > Department form:

**Steps to Reproduce**
- From the left navigation menu, select Department.
- Click on the "Create Department" button.
- Fill in all the required information.
- Click on the "Save Department" button.
- The department is created successfully.
- Click on the "Modify" button to edit the newly created department.

**Actual Result**
- The Ministry, Directorate, Governorate, District and the Sub-District fields doesn't save the values previously selected by the user. (See attached screenshot)
- If you attempt to save, you get the following error message: "Error updating the Department:Input string was not in a correct format." and therefore, you need to re-select values for these fields. 

**Expected Result**
The Ministry, Directorate, Governorate, District and the Sub-District fields should save the values previously selected by the user.

![manage-departments](https://cloud.githubusercontent.com/assets/3637417/5833439/db623a04-a15b-11e4-8e6f-9bbebf57ccde.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
This issue is still reproducible for both the "Manage School" and the "Manage Department" forms.

**Comment by RaymondYounan** [comment]
Done for Department too

**Comment by DrJoeHage** [comment]
@RaymondYounan  and @tannourynadine from a best practice perspective, one issue should not become a thread of issues. The issue should be closed then a new one created instead of using the same issue and drilling down into a set of related issues. Schools and Departments are different code but we need to verify them using the same issue. Does not make sense! So, @tannourynadine please verify and close.

**Comment by tannourynadine** [comment]
- This issue is still reproducible for the "Manage School" form. Create a new school then attempt to modify the newly created school and notice that the "Country" field is empty and you need to reselect a value.
- Verified that this issue is no longer reproducible for the "Manage Department" form.

**Comment by RaymondYounan** [comment]
Done
