### ISSUE TITLE
P2: Application Administration > Grade Section > Unusable in real life scenario

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#182]
You are showing a Section dropdown in the Create Section form.
In real life, the Section is created for specific grade inside an Education Center (Literacy Center or School).
Also, the Term dropdown is showing all the names of the Terms for all the Centers. Long list of the same strings "First Term".
This makes it unusable.

**Comment by RaymondYounan** [comment]
@DrJoeHage What do you suggest we do?

**Comment by DrJoeHage** [comment]
@RaymondYounan There should be a lookup for the Education Center that we are adding a Section in. Then, the Terms list will be restricted to only those Terms applicable to the specific EducCenter. Note that EducGradeSection has EducCenterTermID as FK in it, and the EducCenterTerm table has EducCenterID as FK in it.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the Section drop down is no longer available. However, the Term field is still showing duplicate entries.

**Comment by RaymondYounan** [comment]
@tannourynadine These are not duplicate entries, this is how the entries are in the database 
![image](https://cloud.githubusercontent.com/assets/9402560/6310544/9d77a888-b960-11e4-88bd-bda0bd865dae.png)

**Comment by tannourynadine** [comment]
Closing this issue per Raymond's comment.
