### ISSUE TITLE
P3: Global Administration > Country > Issues encountered while updating a Country

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#186]
Please find below the list of issues encountered while updating a country:
- The following error message is generated when the user tries to update the "Country Code" field:
  "Error in updating the Country:Validation failed for one or more entities. See 'EntityValidationErrors' property for more details."
- A success message is generated when the user tries to update the "Country Type" field and the field wont get updated.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
The issues mentioned in my previous comment are still reproducible.

**Comment by RaymondYounan** [comment]
Country Code should be only 2 characters and cannot be empty. Error messages updated accordingly
Update also fixed

**Comment by tannourynadine** [comment]
- Verified that no error message is generated when the user tries to update the "Country Code" field.
- Verified that the user is able to update the "Country Type" field.
