### ISSUE TITLE
P3: Global Administratiion > Country > An error message is generated when the user tries to create a Country

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#201]
The following error message is generated and the user is not able to create a new country:
"حصل خطأ أثناء إنشاء الدولة:Validation failed for one or more entities. See 'EntityValidationErrors' property for more details."

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
This issue is still reproducible:
"Error in creating Country:Validation failed for one or more entities. See 'EntityValidationErrors' property for more details."

**Comment by RaymondYounan** [comment]
The country type is a required field. Just select a country type and you will be able to insert a new country.
Error Message was updated accordingly

**Comment by tannourynadine** [comment]
Verified that this issue is no longer reproducible.
