### ISSUE TITLE
P2: System Administration > Education Progression Path > An error is generated when the user clicks on the "Education Progression Path" Link available in the left navigation menu

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#203]
![education-progression-path](https://cloud.githubusercontent.com/assets/3637417/5853264/8a8703ba-a22a-11e4-9de3-a2c50e4eaf73.png)

**Comment by RaymondYounan** [comment]
Can you please provide me with the link that you are accessing?

**Comment by tannourynadine** [comment]
http://eaci.joe.me:8088/LookupsManagement/EducProgressionPath/Index

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Tested today for both the EACI and LEMIS instances and found that this issue is still reproducible.

**Comment by RaymondYounan** [comment]
Fixed. You can test it now

**Comment by tannourynadine** [comment]
Verified no error is generated when the user clicks on the "Education Progression Path" Link available in the left navigation menu.
