### ISSUE TITLE
P1: Centers > Education Centers > Need to store EducTypeID in the table.

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#215]
Depending on the AppType, if creating a new Education Center, the EducTypeID should be stored in the EducCenter table record. Currently, it is a NULL. This field will server as a filter for displaying the Education Center listing based on AppType.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Issue not fixed. See also #220. Unable to save a new ALP Center or a new Literacy Center.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Please see my comment in issue #220

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that the user is able to create, modify and delete an Education Center.
- Verified that if the user creates an education center in LEMIS mode, it doesn't appear in EACI mode and vice versa.
- Verified that a popup delete confirmation dialogue is generated, when the user clicks on the "Delete" button.
