### ISSUE TITLE
P3: Exam Management > Exam Dates > The user is not able to postpone an Exam

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#286]
In the "Show Exam Dates", the user should be able Postpone an Exam. Currently he is only able to Complete or Cancel an Exam.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Problem still there.
![exam-date](https://cloud.githubusercontent.com/assets/9402931/9830485/b8d4e708-5938-11e5-8b2c-2398715f1ba4.jpg)

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
