### ISSUE TITLE
P2: System Management Reports are missing from application

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#305]
These are needed for validating the data entered. Refer to the FRS:
• System Roles List
• User Roles List
• Users List
• Activity Frequency List
• Activity Type List
• Attendance Excuse List
• Building Independence List
• Building Ownership List
• Building Quality List
• Building Service List
• Country Sovereignty List
• Country Sub-Type List
• Country Type List
• Days of the Week List
• Dropout Reason List
• Education Center Gender List
• Education Center Type List
• Education Stage List
• Education Type List
• Environment Type List
• Exam Date Status List
• Exam Result List
• Exam Status List
• Facility, School, and Center Status List
• Facility Type List
• Gender List
• Health Record List
• Hearing Test Specifications List
• Language List
• Language Proficiency Level List
• Logical Answer List
• Marital Status List
• Object Status List
• Personal Attribute List
• Position Title List
• Problem Type List
• Registration Status List
• Schedule List
• Session Status List
• Social Status List
• Speech Test Specifications List
• Staff Assignment Type List
• Staff Type List
• Student Education Level List
• Student Failure Reasons List
• Student Literacy Level List
• Student Status List
• Teacher Education Level List
• Term List
• Term Status List
• University Major List
• Vision Test Specifications List

**Comment by RaymondYounan** [comment]
Done.
Please check the script "Additional Menu Items.sql" for the menu items.
Also note that there's additional Resources

**Comment by DrJoeHage** [comment]
Still missing:
University and College List
Student Classification List

**Comment by RaymondYounan** [comment]
Done. You need to add 2 Menu items. Script is uploaded into Dropbox

**Comment by crossonrose-at-yahoo-dot-com** [comment]
![image](https://user-images.githubusercontent.com/61810389/76657576-2d448900-6540-11ea-989f-0534e43abea8.png)
