### ISSUE TITLE
P4: Facilities > Manage Facility Administrators > Incorrect Page Title and Create button text is displayed.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#75]
Since the user is managing facility administrators the page title and create button should be updated from "Manage Center Administrators" to "Manage Facility Administrators" and the create button should be updated from "Create Center Administrators" to "Create Facility Administrators".

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
This issue is still reproducible, please see my comment in issue #76

**Comment by DrJoeHage** [comment]
Fixed. @tannourynadine You may close this issue and go ahead and take screen shots.

**Comment by tannourynadine** [comment]
Verified that in the manage facility administrators the page title and create button are updated from "Manage Center Administrators" to "Manage Facility Administrators" and the create button is updated from "Create Center Administrators" to "Create Facility Administrators".
