### ISSUE TITLE
P4: Facilities > Manage Facility Administrators > Incorrect Page Titles are displayed at the Create a facility Administrator popup dialog.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#76]
The page titles should be updated from "Manage Center Administrators" and "Create Center Administrator" to "Manage Facility Administrators" and "Create Facility Administrator" since the user is creating a facility administrator.
**Note** This issue is also reproducible for the Edit facility administrator.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
This issue is still reproducible in the manage, create and edit facility administrators pages. (See attached Screenshots)
![facility-administrators-1](https://cloud.githubusercontent.com/assets/3637417/5613619/d899c904-94ef-11e4-8e9f-bebdce17816b.png)

![facility-administrators-2](https://cloud.githubusercontent.com/assets/3637417/5613621/d8a1b786-94ef-11e4-893f-f047dfc37a9a.png)

![facility-administrators-3](https://cloud.githubusercontent.com/assets/3637417/5613620/d8a09ca2-94ef-11e4-98b5-0abab5e55fab.png)

**Comment by DrJoeHage** [comment]
http://localhost:50066/CenterManagement/ManageCenterAdmin/Index
There is no FacilityManagement area in the source code.
Also, there are only 3 views under CenterManagement:
1. ManageCenterAdmin
2. ManageEducCenterAdmin
3. ManageSchoolAdmin

There is no ManageFacilityAdmin view there. @RaymondYounan: So, what would you like me to do?

**Comment by RaymondYounan** [comment]
@DrJoeHage, just update the strings. If you deem that we need to change the page name, I can do it too

**Comment by DrJoeHage** [comment]
Fixed. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
Updated the LEMIS and EACI user guides with updated screenshots of the "Manage Facility Administrators" form.
