### ISSUE TITLE
P4: Application Administration > Exam > A Horizontal scrolling bar is needed to enable the user to see the hidden text for the "Actions" tab.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#99]
A vertical scrolling bar is needed to enable the user to see the hidden text for the "Actions" tab. (See attached screenshot)

![exam-2](https://cloud.githubusercontent.com/assets/3637417/5626932/794f298e-959a-11e4-8468-622a46126a19.png)

**Comment by Rfarran** [comment]
Done

**Comment by tannourynadine** [comment]
The horizontal scrolling bar is hiding the Action's list menu and the user is not able to perform any action. Please see attached screenshot.

![exam](https://cloud.githubusercontent.com/assets/3637417/5916654/12a4e592-a61c-11e4-93d9-a4088288645f.png)

**Comment by tannourynadine** [comment]
This issue is still reproducible, the "Actions" drop down list is hidden and the user is not able to apply an action. @Rfarran
